"""deployment container fields

Revision ID: 8c2906176da4
Revises: 3bda80bb4ee0
Create Date: 2026-07-09 21:19:04.666167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c2906176da4'
down_revision: Union[str, Sequence[str], None] = '3bda80bb4ee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('container_name', sa.Text(), nullable=True))
    op.add_column('deployments', sa.Column('router_priority', sa.Integer(), nullable=True))
    op.add_column('deployments', sa.Column('deploy_started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deployments', 'deploy_started_at')
    op.drop_column('deployments', 'router_priority')
    op.drop_column('deployments', 'container_name')
    # ### end Alembic commands ###
